# BUAN 6312 - Group 1 - Data Preprocessing

### Impact of environmental and seasonal factors on bike rental demand

In [42]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [43]:
df = pd.read_csv('day.csv')

In [44]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [45]:
categorical_columns = ['season', 'mnth', 'weekday', 'weathersit']

# Perform one-hot encoding
for col in categorical_columns:
    dummies = pd.get_dummies(df[col], prefix=col)
    df = pd.concat([df, dummies], axis=1)

# Convert dummy columns to integers (0 or 1)
dummy_columns = [col for col in df.columns if '_' in col]  
df[dummy_columns] = df[dummy_columns].astype(int)

# Normalize the 'cnt' variable using Min-Max scaling
scaler = MinMaxScaler()
df['cnt'] = scaler.fit_transform(df[['cnt']])

# Print the processed DataFrame
print(df)

# Save the preprocessed DataFrame to a new CSV file
df.to_csv('day_preprocessed.csv', index=False)

     instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0          1  2011-01-01       1   0     1        0        6           0
1          2  2011-01-02       1   0     1        0        0           0
2          3  2011-01-03       1   0     1        0        1           1
3          4  2011-01-04       1   0     1        0        2           1
4          5  2011-01-05       1   0     1        0        3           1
..       ...         ...     ...  ..   ...      ...      ...         ...
726      727  2012-12-27       1   1    12        0        4           1
727      728  2012-12-28       1   1    12        0        5           1
728      729  2012-12-29       1   1    12        0        6           0
729      730  2012-12-30       1   1    12        0        0           0
730      731  2012-12-31       1   1    12        0        1           1

     weathersit      temp  ...  weekday_0  weekday_1  weekday_2  weekday_3  \
0             2  0.344167  ...          0          0          0          0
1             2  0.363478  ...          1          0          0          0
2             1  0.196364  ...          0          1          0          0
3             1  0.200000  ...          0          0          1          0
4             1  0.226957  ...          0          0          0          1
..          ...       ...  ...        ...        ...        ...        ...
726           2  0.254167  ...          0          0          0          0
727           2  0.253333  ...          0          0          0          0
728           2  0.253333  ...          0          0          0          0
729           1  0.255833  ...          1          0          0          0
730           2  0.215833  ...          0          1          0          0

     weekday_4  weekday_5  weekday_6  weathersit_1  weathersit_2  weathersit_3
0            0          0          1             0             1             0
1            0          0          0             0             1             0
2            0          0          0             1             0             0
3            0          0          0             1             0             0
4            0          0          0             1             0             0
..         ...        ...        ...           ...           ...           ...
726          1          0          0             0             1             0
727          0          1          0             0             1             0
728          0          0          1             0             1             0
729          0          0          0             1             0             0
730          0          0          0             0             1             0

[731 rows x 42 columns]

In [48]:
csv_file = "day_preprocessed.csv" 
df = pd.read_csv(csv_file)

dta_file = "day_preprocessed.dta" 
df.to_stata(dta_file, write_index=False)

In [49]:
print(df.columns)

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt', 'season_1', 'season_2', 'season_3',
       'season_4', 'mnth_1', 'mnth_2', 'mnth_3', 'mnth_4', 'mnth_5', 'mnth_6',
       'mnth_7', 'mnth_8', 'mnth_9', 'mnth_10', 'mnth_11', 'mnth_12',
       'weekday_0', 'weekday_1', 'weekday_2', 'weekday_3', 'weekday_4',
       'weekday_5', 'weekday_6', 'weathersit_1', 'weathersit_2',
       'weathersit_3'],
      dtype='object')